name: Formatting

on: push

jobs:
  black-formatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run black formatter
        uses: psf/black@stable
        with:
          options: "--check --diff --color"
          src: "./proxyllm"
          version: "~= 22.0"
