name: Secrets Scan

on: push

jobs:
  scannner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
